

SET DEFINE OFF SPOOL XXL - JOB - SQL3.LOG

CREATE TABLE XXL_JOB_QRTZ_JOB_DETAILS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,JOB_NAME VARCHAR2(600) NOT NULL
	,JOB_GROUP VARCHAR2(600) NOT NULL
	,DESCRIPTION VARCHAR2(750)
	,JOB_CLASS_NAME VARCHAR2(750) NOT NULL
	,IS_DURABLE VARCHAR2(1) NOT NULL
	,IS_NONCONCURRENT VARCHAR2(1) NOT NULL
	,IS_UPDATE_DATA VARCHAR2(1) NOT NULL
	,REQUESTS_RECOVERY VARCHAR2(1) NOT NULL
	,JOB_DATA BLOB
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_JOB_DETAILS ADD CONSTRAINT PRIMARYKEY8 PRIMARY KEY (
	SCHED_NAME
	,JOB_NAME
	,JOB_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,JOB_NAME VARCHAR2(600) NOT NULL
	,JOB_GROUP VARCHAR2(600) NOT NULL
	,DESCRIPTION VARCHAR2(750)
	,NEXT_FIRE_TIME NUMBER(13)
	,PREV_FIRE_TIME NUMBER(13)
	,PRIORITY NUMBER(11)
	,TRIGGER_STATE VARCHAR2(48) NOT NULL
	,TRIGGER_TYPE VARCHAR2(24) NOT NULL
	,START_TIME NUMBER(13)
	,END_TIME NUMBER(13)
	,CALENDAR_NAME VARCHAR2(600)
	,MISFIRE_INSTR NUMBER(2)
	,JOB_DATA BLOB
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_TRIGGERS ADD CONSTRAINT PRIMARYKEY3 PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_GROUP
	,TRIGGER_NAME
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_SIMPLE_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,REPEAT_COUNT NUMBER(7) NOT NULL
	,REPEAT_INTERVAL NUMBER(12) NOT NULL
	,TIMES_TRIGGERED NUMBER(10) NOT NULL
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT PRIMARYKEY PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_NAME
	,TRIGGER_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_CRON_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,CRON_EXPRESSION VARCHAR2(600) NOT NULL
	,TIME_ZONE_ID VARCHAR2(240)
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_CRON_TRIGGERS ADD CONSTRAINT PRIMARYKEY6 PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_NAME
	,TRIGGER_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_SIMPROP_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,STR_PROP_1 VARCHAR2(1536)
	,STR_PROP_2 VARCHAR2(1536)
	,STR_PROP_3 VARCHAR2(1536)
	,INT_PROP_1 NUMBER(11)
	,INT_PROP_2 NUMBER(11)
	,LONG_PROP_1 NUMBER(20)
	,LONG_PROP_2 NUMBER(20)
	,DEC_PROP_1 NUMBER(13, 4)
	,DEC_PROP_2 NUMBER(13, 4)
	,BOOL_PROP_1 VARCHAR2(1)
	,BOOL_PROP_2 VARCHAR2(1)
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255;

ALTER TABLE XXL_JOB_QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT PRIMARYKEY2 PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_NAME
	,TRIGGER_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255;

CREATE TABLE XXL_JOB_QRTZ_BLOB_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,BLOB_DATA BLOB
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255;

ALTER TABLE XXL_JOB_QRTZ_BLOB_TRIGGERS ADD CONSTRAINT PRIMARYKEY4 PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_NAME
	,TRIGGER_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255;

CREATE TABLE XXL_JOB_QRTZ_PAUSED_TRIGGER_GRPS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255;

ALTER TABLE XXL_JOB_QRTZ_PAUSED_TRIGGER_GRPS ADD CONSTRAINT PRIMARYKEY11 PRIMARY KEY (
	SCHED_NAME
	,TRIGGER_GROUP
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255;

CREATE TABLE XXL_JOB_QRTZ_FIRED_TRIGGERS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,ENTRY_ID VARCHAR2(300) NOT NULL
	,TRIGGER_NAME VARCHAR2(600) NOT NULL
	,TRIGGER_GROUP VARCHAR2(600) NOT NULL
	,INSTANCE_NAME VARCHAR2(600) NOT NULL
	,FIRED_TIME NUMBER(13)
	,SCHED_TIME NUMBER(13) NOT NULL
	,PRIORITY NUMBER(11) NOT NULL
	,STATE VARCHAR2(48) NOT NULL
	,JOB_NAME VARCHAR2(600)
	,JOB_GROUP VARCHAR2(600)
	,IS_NONCONCURRENT VARCHAR2(1)
	,REQUESTS_RECOVERY VARCHAR2(1)
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_FIRED_TRIGGERS ADD CONSTRAINT PRIMAYKEY7 PRIMARY KEY (
	SCHED_NAME
	,ENTRY_ID
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_SCHEDULER_STATE (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,INSTANCE_NAME VARCHAR2(600) NOT NULL
	,LAST_CHECKIN_TIME NUMBER(13) NOT NULL
	,CHECKIN_INTERVAL NUMBER(13) NOT NULL
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_SCHEDULER_STATE ADD CONSTRAINT PRIMARYKEY10 PRIMARY KEY (
	SCHED_NAME
	,INSTANCE_NAME
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_LOCKS (
	SCHED_NAME VARCHAR2(360) NOT NULL
	,LOCK_NAME VARCHAR2(120) NOT NULL
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_LOCKS ADD CONSTRAINT PRIMARYKEY9 PRIMARY KEY (
	SCHED_NAME
	,LOCK_NAME
	) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_TRIGGER_INFO (
	ID NUMBER(11) NOT NULL
	,JOB_GROUP NUMBER(11) NOT NULL
	,JOB_CRON VARCHAR2(384) NOT NULL
	,JOB_DESC VARCHAR2(765) NOT NULL
	,ADD_TIME DATE
	,UPDATE_TIME DATE
	,AUTHOR VARCHAR2(192)
	,ALARM_EMAIL VARCHAR2(765)
	,EXECUTOR_ROUTE_STRATEGY VARCHAR2(150)
	,EXECUTOR_HANDLER VARCHAR2(765)
	,EXECUTOR_PARAM VARCHAR2(1536)
	,EXECUTOR_BLOCK_STRATEGY VARCHAR2(150)
	,EXECUTOR_TIMEOUT NUMBER(11) DEFAULT 0 NOT NULL
	,EXECUTOR_FAIL_RETRY_COUNT NUMBER(11) DEFAULT 0 NOT NULL 
	,GLUE_TYPE VARCHAR2(150) NOT NULL
	,GLUE_SOURCE CLOB
	,GLUE_REMARK VARCHAR2(384)
	,GLUE_UPDATETIME DATE
	,CHILD_JOBID VARCHAR2(765)
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_TRIGGER_INFO ADD PRIMARY KEY (ID) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_TRIGGER_LOG (
	ID NUMBER(11) NOT NULL
	,JOB_GROUP NUMBER(11) NOT NULL
	,JOB_ID NUMBER(11) NOT NULL
	,EXECUTOR_ADDRESS VARCHAR2(765)
	,EXECUTOR_HANDLER VARCHAR2(765)
	,EXECUTOR_PARAM VARCHAR2(1536)
	,EXECUTOR_SHARDING_PARAM varchar2(60) DEFAULT NULL
	,EXECUTOR_FAIL_RETRY_COUNT NUMBER(11) DEFAULT 0 NOT NULL
	,TRIGGER_TIME DATE
	,TRIGGER_CODE VARCHAR2(765) DEFAULT 0 NOT NULL
	,TRIGGER_MSG CLOB
	,HANDLE_TIME DATE
	,HANDLE_CODE VARCHAR2(765) DEFAULT 0 NOT NULL
	,HANDLE_MSG CLOB
	,ALARM_STATUS NUMBER(4) DEFAULT 0 NOT NULL
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_TRIGGER_LOG ADD PRIMARY KEY (ID) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

CREATE TABLE XXL_JOB_QRTZ_TRIGGER_LOGGLUE (
	ID NUMBER(11) NOT NULL
	,JOB_ID NUMBER(11) NOT NULL
	,GLUE_TYPE VARCHAR2(150)
	,GLUE_SOURCE CLOB
	,GLUE_REMARK VARCHAR2(384)
	,ADD_TIME DATE
	,UPDATE_TIME DATE
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255;

ALTER TABLE XXL_JOB_QRTZ_TRIGGER_LOGGLUE ADD PRIMARY KEY (ID) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255;

CREATE TABLE XXL_JOB_QRTZ_TRIGGER_REGISTRY (
	ID NUMBER(11) NOT NULL
	,REGISTRY_GROUP VARCHAR2(765) NOT NULL
	,REGISTRY_KEY VARCHAR2(765) NOT NULL
	,REGISTRY_VALUE VARCHAR2(765) NOT NULL
	,UPDATE_TIME DATE
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255;

ALTER TABLE XXL_JOB_QRTZ_TRIGGER_REGISTRY ADD PRIMARY KEY (ID) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255;

CREATE TABLE XXL_JOB_QRTZ_TRIGGER_GROUP (
	ID NUMBER(11) NOT NULL
	,APP_NAME VARCHAR2(192) NOT NULL
	,TITLE VARCHAR2(36) NOT NULL
	,GROUP_ORDER NUMBER(4) DEFAULT 0
	,ADDRESS_TYPE NUMBER(4) DEFAULT 0 NOT NULL
	,ADDRESS_LIST VARCHAR2(1536)
	) TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

ALTER TABLE XXL_JOB_QRTZ_TRIGGER_GROUP ADD PRIMARY KEY (ID) USING INDEX TABLESPACE SCHEDUAL_JOB PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 64 K NEXT 1 M MINEXTENTS 1 MAXEXTENTS UNLIMITED);

--CREATE SEQUENCE
CREATE SEQUENCE JOB_KEY_SEQUENCE MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1 CACHE 20;


INSERT INTO  XXL_JOB_QRTZ_TRIGGER_GROUP ( id ,  app_name ,  title ,  GROUP_ORDER ,  address_type ,  address_list ) VALUES (1, 'xxl-job-executor-sample', '示例执行器', 1, 0, NULL);
INSERT INTO  XXL_JOB_QRTZ_TRIGGER_INFO ( id ,  job_group ,  job_cron ,  job_desc ,  add_time ,  update_time ,  author ,  alarm_email ,  executor_route_strategy ,  executor_handler ,  executor_param ,  executor_block_strategy ,  executor_timeout ,  executor_fail_retry_count ,  glue_type ,  glue_source ,  glue_remark ,  glue_updatetime ,  child_jobid ) VALUES (1, 1, '0 0 0 * * ? *', '测试任务1', to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), 'XXL', '', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), '');


SPOOL OFF
	
